# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-16 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_email', '0005_emailmessage_retries'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='error',
            field=models.BooleanField(default=False, verbose_name='Error'),
        ),
    ]
