# Generated by Django 5.0.6 on 2024-06-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codenerix_email", "0009_emailmessage_opened_emailmessage_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessage",
            name="content_subtype",
            field=models.CharField(
                blank=True,
                choices=[("plain", "Plain"), ("html", "HTML")],
                default="html",
                max_length=256,
                verbose_name="Content Subtype",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="content_subtype",
            field=models.CharField(
                blank=True,
                choices=[("plain", "Plain"), ("html", "HTML")],
                default="html",
                max_length=256,
                verbose_name="Content Subtype",
            ),
        ),
    ]
